export enum USER_MODE {
	ENQUIRY = "ENQUIRY",
	ARCHIVE = "ARCHIVE",
	FREEZE = "FREEZE",
	PREBOOK = "PREBOOK",
	ACTIVE = "ACTIVE",
	PENDING = "PENDING",
	COMPLETE = "COMPLETE",
	BANNED = "BANNED",
	TEMPORARY = "TEMPORARY",
}