// TODO: make neutron proxy this
export enum DEVICE_STATE{
	PAUSE = "PAUSE",
	ONLINE = "ONLINE",
	COMMUNICATING = "COMMUNICATING",
	OFFLINE = "OFFLINE",
	NOT_AUTHORIZED = "NOT_AUTHORIZED",
	ERROR = "ERROR",
	PUSH_COMM_KEY_ERR = "PUSH_COMM_KEY_ERR",
}
